### ISSUE TITLE
Linuxbrew update

### ISSUE THREAD

**Issue by Vlaaaaaaad** [gitpod-io/workspace-images#161]
Hi,

I'd add a warning somewhere: if building an image on top of `workspace-full` then do run a `brew update` as a first step.

I am maintaining two Gitpod images: [Terraform](https://github.com/Vlaaaaaaad/gitpod-terraform) and [Helm](https://github.com/Vlaaaaaaad/gitpod-helm) dev images. I was **very** _very_ very confused why on earth Gitpod would:
- install `terraform-docs` v6 instead of v8
- complain that there's no `helm@2` cask

After I ignored the issues for about a week, I went investigating.
Running and building the image locally would use the correct versions and not fail at all. After way too much time debugging, I figured out that I should run an `update` before installing any new software in my custom Dockerfile.

As soon as I did that, everything worked as expected. 

In the interest of saving someone else the pain, could a `brew update` command be added to the base Gitpod images? Or at least a disclaimer to run that for any custom images?

**Comment by jankeromnes** [comment]
Hi @Vlaaaaaaad, wow, thank you so much for getting to the bottom of these weird issues.

Our Docker builds are cached by component (or Dockerfile "section"), so we have to update each Dockerfile section independently in order to keep it up-to-date.

It looks like the Homebrew section cache is too old now, so I'll update it today. This should fix your issues, for you and everyone else using `brew` in Gitpod.

I'll also try to remember updating it regularly in order to prevent new similar issues. (Unfortunately, I don't know a better way than manual cache invalidation yet. Also FYI, we've disabled Homebrew's default auto-update feature, because it was making every `brew` call unusably slow.)

**Comment by jankeromnes** [comment]
I think this should be fixed by https://github.com/gitpod-io/workspace-images/commit/1fdebddfc3ec84cc71845ee2624d2f803d110986 (this unrelated-looking commit invalidates the cache for the Homebrew install, or at least for the `brew install cmake` below, which should auto-update Homebrew, because we only disable that afterwards).

Once deployed, I'll try to confirm by installing `terraform-docs` (v8) and `helm@2`.

**Comment by Vlaaaaaaad** [comment]
Hm... considering `HOMEBREW_NO_AUTO_UPDATE=1` is set after a `brew install` I think that it may indeed solve it, yup.

How often are workspace images updates though? I still see the value in a _Run a brew update in your custom dockerfiles_ note somewhere. 
I am thinking of linters/ formatters/ etc. I run in Gitpod and then I push the code to GitHub. GitHub Actions does a `brew install` and get a version that was bumped say 2 hours ago. Code that was fine on my machine may fail the CI check which uses a new version.

**Comment by jankeromnes** [comment]
> How often are workspace images updates though?

We try to keep every Dockerfile "dazzle" section up-to-date by regularly committing changes to them. This is very manual, and favours the pinning specific versions, but it's a trade-off between efficient Docker caching and always-fresh images.

Before "dazzle", we used to invalidate cache for the entire Dockerfile (or rather, all lines below the topmost modified line) much more frequently, but this caused increased disk usage in our clusters. Now that we've cached Dockerfile sections independently, we can update the Dockerfile sections to need it, and keep the other sections cached for longer, thus using less disk space.

Please let me know if you have thoughts/ideas on our approach here.

> I still see the value in a _Run a brew update in your custom dockerfiles_ note somewhere.

I agree. Maybe in https://www.gitpod.io/docs/config-docker/#creating-docker-images-for-gitpod or in https://www.gitpod.io/blog/brew/ ?

**Comment by jankeromnes** [comment]
Seems to work better now!

<img width="720" alt="Screenshot 2020-02-10 at 16 44 41" src="https://user-images.githubusercontent.com/599268/74166016-359a6300-4c26-11ea-901b-507a5cedffa3.png">

**Comment by jankeromnes** [comment]
However, `brew install terraform-docs` gave me `7.0.0` for some reason.

After running `brew update` (which took a very long time), `brew upgrade terraform-docs` was able to give me `0.8.2`.

Not sure from when the current Homebrew version is. 🤔

**Comment by jankeromnes** [comment]
Just tested in https://gitpod.io/#https://github.com/jankeromnes/MetaChess :

```
$ brew --version
Homebrew 2.2.13
Homebrew/linuxbrew-core (git revision 299f4; last commit 2020-04-15)

$ brew install terraform-docs
==> Downloading https://linuxbrew.bintray.com/bottles/terraform-docs-0.9.1.x8
==> Downloading from https://akamai.bintray.com/6e/6e334093765074a15463191e49
###################################                                       48.##########################################################                81.######################################################################## 100.0%
==> Pouring terraform-docs-0.9.1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/terraform-docs/0.9.1: 8 files, 10.7MB
```

So LinuxBrew seems to have been updated. 🎉 

If it ever gets out-dated again, please:

1. If your repository uses a [custom Gitpod Dockerfile](https://www.gitpod.io/docs/config-docker/#using-a-dockerfile), commit any change to it to invalidate Gitpod's cached image (forces Gitpod to actually rebuild the Dockerfile)

2. If that doesn't fix it, please commit any change in Gitpod's HomeBrew installation lines:

https://github.com/gitpod-io/workspace-images/blob/85da3729b4ccd58ed7f71ff943b92262a9d4e3f8/full/Dockerfile#L111-L115

That will trigger a fresh rebuild of the HomeBrew installation in `gitpod/workspace-full` and all dependent images (should get published within 1 hour -- after which you may want to try 1. again).
